tprouvot/Salesforce-Inspector-reloaded

- addon/data-load.css
- addon/data-load.js
- addon/images/copy.svg
Add functionnality to copy id to clipboard in export data table
> Add copy to clipboard functionnality

- addon/data-export.css
> Fix table head on export

- CHANGES.md
- addon/button.js
- addon/data-import.js
- addon/manifest-template.json
- addon/manifest.json
Upgrade extension manifest version
> feature use manifest v3

- addon/data-export.css
- addon/data-export.js
> Add export title on same line as select

- CHANGES.md
- addon/popup.js
> [feat] Add / Update links on popup

- README.md
- package-lock.json
We had some dependabot alerts on the repo which has to be solved
> [feat] Update dependencies

- CHANGES.md
- addon/popup.js
> [fix] popup : Object links for custom metadata

- addon/popup.js
> [feat] Improve links display in popup

- CHANGES.md
- addon/manifest-template.json
- addon/popup.js
> [popup] User : Add "PSet" button for user

- CHANGES.md
- addon/inspector.js
- addon/manifest.json
- addon/popup.css
- addon/popup.js
> [general] feature : Allow user to update api version

- CHANGES.md
- addon/data-import.js
> [data-import] Select update action when paste has Id column

- .gitignore
- addon/data-export.js
> [fix] Typo data export

- CHANGES.md
- addon/data-import.js
> [fix] Import action auto update

- CHANGES.md
- addon/data-import.js
> [data-import] Import as json

- CHANGES.md
- addon/inspect.js
> [feat] Inspect :  Show copy id from inspect view

- CHANGES.md
- addon/data-export.js
> Add toLabel function among suggested autocomplete options

- CHANGES.md
- addon/popup.js
Fixed wrong reference to ReactJS component refs
> [96] Fix ctrl+m, ctrl+a shortcuts

- CHANGES.md
- addon/popup.js
> [popup] Use custom shortcuts

- CHANGES.md
- addon/popup.js
> [popup] Search for metadata records (Flow, Profile, PermissionSet)

- CHANGES.md
- addon/data-export.js
> [data-export] Add 'LIMIT 200' when selecting 'FIELDS' in autocomplete

- CHANGES.md
- addon/inspect.js
- addon/setup-links.js
> [show-all-data] Fix field setup link from show all data

- CHANGES.md
- addon/popup.js
> [popup] feature : Display record name in popup

- CHANGES.md
- addon/inspect.js
> Fix edit layout link

- CHANGES.md
- addon/manifest-template.json
- addon/manifest.json
- addon/popup.css
- addon/popup.js
> Add soap doc on object

- CHANGES.md
- addon/inspect.css
After editing the field, the button section in the footer is now centred.
> Centering footer buttons.

- CHANGES.md
- addon/data-import-test.js
- addon/data-import.js
Undelete records from data-import page
#193
> [data-import] Undelete records

- CHANGES.md
- addon/popup.css
> [BETA] minor fix on generate token style

- addon/background.js
#281 introduces a regression on .mil domains.
This PR should fix it.
> Fix getSfHost in .mil domains

- CHANGES.md
- addon/data-load.js
I created a new pull request, following @tprouvot suggestion.
Now only when the object is one of the following:
| Object Name | Key Prefix |
| ------------- | ------------- |
| entitlementcontact | 000 |
| entitysubscription | 000 |
| productentitlementtemplate | 000 |
| casecomment | 00a |
| ideacomment | 00a |
| accountpartner | 00I |
| opportunitypartner | 00I |
| partner | 00I |
| leadstatus | 01J |
| opportunitystage | 01J |
| contentdocument | 069 |
| contentnote | 069 |
a callout using `/ui-api/records/` is fired to get the exact Object ApiName.
The api has `layoutTypes=Compact` so that not all the layout infos are pulled, but just the compact layout infos. 
In the objects listed above the changes that can be applied to the compact layout are limited, so that I expect the api speed …
> fix: double "Show all data" button

- CHANGES.md
- addon/data-export.css
Make data export suggestions scrollable
Close #301
> Make data export suggestion scrollable

- CHANGES.md
- addon/inspect.js
Align Data Type in Inspector with Salesforce:
#311
> [fix] Show All data : Align Data Type with Salesforce

- CHANGES.md
- addon/popup.js
> [popup] Add recently viewed list 

- CHANGES.md
Moved 1 item from 1.22 to 1.23 in CHANGES.md (since not present in 1.22).
> chore: change moved from 1.22 to 1.23

- addon/popup.js
Display 15-char Org Id in Org Tab (instead of 18-char Id)
Fixes #323
> Display 15-char Org Id

- CHANGES.md
- addon/data-import-test.js
- addon/data-import.js
- addon/options.js
Add the batchSize and thread size to the configurable options.
#329
> Add batch size and thread size to options page

- CHANGES.md
- addon/inspector.js
- addon/popup.js
> [popup] Add expired token text

- CHANGES.md
- addon/button.js
- addon/options.js
- addon/popup.js
Some users requested to enlarge popup width, since this need is not for all users it would be great to have a configuration option for this.
#368
> Add configuration option for popup width

- addon/inspector.js
- addon/popup.js
Add Experience Cloud search in meta shortcut search and access the builder when selecting this option.
#365
> [popup] Search and open experience cloud builder from shortcuts

- CHANGES.md
- addon/inspect.js
Fix popup not closing in inspect page when:
- Clicking outside the popup
**Side note:** I skipped the test on AccountContantRelationship, rest all good (for my POV we can move from AccountContactRelationship to another entity which is available by default, e.g.: AccountEventChange)
[issue 159](https://github.com/tprouvot/Salesforce-Inspector-reloaded/issues/159)
> Fix popup not closing in inspect page

- addon/button.js
- addon/options.js
- addon/popup.js
Customize environment favicon
Closes #180
> [feat] #180 Customize org favicon

- CHANGES.md
- addon/popup.js
I’ve added a line to trim the user input in the getMatches function. This prevents issues caused by leading or trailing spaces in the input.
https://github.com/tprouvot/Salesforce-Inspector-reloaded/issues/410
> Trim user search

- addon/button.js
- addon/data-import.js
- addon/inspector.js
- addon/options.js
Bug fix and enhancements for favicons to fix prior PR
- restored option to enable/disable favicons
- removed toggle from text input Option type
- added isFavIcon prop to enable favicon specific text feature  - icon preview
- [ x ] I have read and understand the [Contributions section](https://github.com/tprouvot/Salesforce-Inspector-reloaded#contributions)
- [ x ] Target branch is releaseCandidate and not master
- [ x ] I have performed a self-review of my code
- [ x ] I ran the [unit tests](https://github.com/tprouvot/Salesforce-Inspector-reloaded#unit-tests) and my PR does not break any tests
- [ n/a ] I documented the changes I've made on the [CHANGES.md](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/master/CHANGES.md) and followed actual conventions
- [ n/a ] I added …
> [general] Favicon bug fix and enhancement

- CHANGES.md
- addon/data-export.js
Filter record type names suggestion to sobject context
Closes #442
> [data-export] Filter record type names suggestion to SObject context

- addon/popup.js
Fix the LoginAs button
Fix #457
> Fix the LoginAs button

- CHANGES.md
- addon/button.js
Improve screen reader compatibility
#454
> [general] Improve screen reader compatibility

- CHANGES.md
- addon/data-export.js
Support new query languages (SOSL, GraphQL)
Closes #131
> Support new query languages (SOSL, GraphQL)

- CHANGES.md
- addon/data-export.js
- addon/inspector.js
> Beta release

- CHANGES.md
- addon/popup.js
Add condition for customSettings
Fix error label display in component
473
- [] I documented the changes I've made on the [CHANGES.md](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/master/CHANGES.md) and followed actual conventions
- [] I added a new section on [how-to.md](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/master/docs/how-to.md) (optional)
> Custom settings and label

- CHANGES.md
- addon/data-import.css
- addon/data-import.js
- addon/options.js
- docs/how-to.md
Allow users to define custom headers on data import page for soap callout
Fix #478
> [feat] Add custom headers to data import

- CHANGES.md
- addon/manifest-template.json
- addon/manifest.json
- addon/popup.js
> Fix links for platform events

- CHANGES.md
- addon/button.js
- addon/manifest-template.json
- addon/manifest.json
> Enable reloaded on experience builder site

- addon/event-monitor.css
- addon/event-monitor.js
- addon/popup.js
- docs/event-monitor.md
- Refactor subscription & cache channels list.
- Improve subscription steps.
- Add error message in case of subscription failed.
- Add URL args to implement short cut from Platform Event object.
> [event-monitor] refactor subscription & cache channels

- addon/event-monitor.js
Add Spinner during the subscription.
Disable cometd debug.
> [event-monitor] Add subscription spinner & disable cometd debug

- addon/field-creator.js
> Fix Bug #575

- CHANGES.md
- addon/options.js
- docs/how-to.md
Add the import / export functionnality
Fix #570
> Add import / Export configuration from the options page

- addon/field-creator.js
Removed storing in session cache as this solution is not implemented aand will not be a sufficient solution due to sessionstorage limitations
> Remove unused Cache.

- addon/field-creator.js
Now select all will only apply to the filtered items. Improving usability.
> [field-creator] Improve Select All Permissions

- addon/field-creator.js
- package-lock.json
- package.json
Added some asyncrony on this.
#613
> [field-creator]  Permision fix

- addon/data-load.js
- package-lock.json
- package.json
Previous approach did not correctly consider the sizes of the table. Now the headers are rendered independently, sizes for render are calculated based on dynamic sizes.
https://github.com/tprouvot/Salesforce-Inspector-reloaded/issues/514
> [field-creator]  Reworking table for viewport size

- CHANGES.md
- addon/data-export.css
- addon/data-export.js
- addon/data-import.css
- addon/data-load.css
- addon/data-load.js
- addon/event-monitor.css
- addon/event-monitor.js
- addon/field-creator.css
- addon/field-creator.js
- addon/inspect.css
- addon/inspector.js
- addon/links.js
- addon/manifest-firefox.json
- addon/options.css
- addon/options.js
- addon/popup.css
- addon/popup.js
- addon/rest-explore.css
- addon/rest-explore.js
- package-lock.json
- package.json
> BETA last release 1.25

- CHANGES.md
- addon/event-monitor.js
- addon/limits.css
- addon/limits.html
- addon/limits.js
> Restyle Org Limits

- CHANGES.md
- addon/links.js
> Add 'My Personal Information' shortcuts

- .github/ISSUE_TEMPLATE/bug_report.md
- CHANGES.md
- addon/background.js
- addon/data-export.js
- addon/manifest-template.json
- addon/manifest.json
- addon/popup.js
- docs/how-to.md
Add custom shortcuts for loading fields and execute query.
#653
> [data-export] Add custom shortcuts

- CHANGES.md
- addon/background.js
- addon/manifest.json
Add chrome extension shortcuts for Setup, Home Page and Dev Console
Closes #707
> [general] Add chrome extension shortcuts for Setup, Home Page and Dev Console

- CHANGES.md
- addon/data-import.js
Guess file format on data import
Fix #501
> [data-import] Guess file format on data import

- CHANGES.md
- addon/button.js
> Fix sandbox color banner missing in Flow debug

- addon/button.js
- addon/popup.js
- docs/how-to.md
Generate package.xml from a DeployRequest
> [popup] Generate package.xml from a DeployRequest

- CHANGES.md
- addon/options.js
> [data-export] Change input field type to textarea field type.

- CHANGES.md
- addon/data-export.js
#773 
- [] I added a new section on [how-to.md](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/master/docs/how-to.md) (optional)
> [data-export] fix #773 Stop button in data export

- CHANGES.md
- addon/rest-explore.js
> Fix bulk api job result display

- CHANGES.md
- addon/components/AlertBanner.js
- addon/popup.css
- addon/popup.js
- docs/how-to.md
> [popup] Add Delete All ApexLogs button

- CHANGES.md
- addon/event-monitor.js
- docs/event-monitor.md
> Support Custom Channels in Event Monitor

- CHANGES.md
- addon/event-monitor.css
- addon/event-monitor.js
- addon/metadata-retrieve.css
- addon/metadata-retrieve.js
- docs/event-monitor.md
> Implement event search and filter on Event Monitor

- CHANGES.md
- addon/inspect.js
> feat: Add boolean toggle functionality in FieldValueCell component

- CHANGES.md
- addon/data-import.js
Don't show errors when deleting Report IDs
#829
> add hard-coded prefix for reports to be deleted

- CHANGES.md
- addon/components/Toast.js
- addon/metadata-retrieve.css
- addon/metadata-retrieve.js
- docs/download-metadata.md
> [feat] Deploy Metadata 
