tprouvot/Salesforce-Inspector-reloaded

- CHANGES.md
- addon/inspector.js
- addon/popup.js
#52 
Org instance is displayed on the bottom of the popup and the link redirect to [trust](https://status.salesforce.com/instances/CS81)
You may have to reload the page on first use to be able to see the org instance
> [popup] Add org instance in the popup and a link to Salesforce trust status website

- CHANGES.md
- addon/data-export.js
> [fix] Set the focus on suggested fields when pressing tab key in query editor

- addon/popup.js
Added slds to deploy page buttons - [issue 103](https://github.com/tprouvot/Salesforce-Inspector-reloaded/issues/103)
> Bug fix/103 slds buttons

- CHANGES.md
- addon/popup.js
The current method isn't handling multiple underscores in LocalSidKey.
There are multiple values with 2 underscores:
- de_DE_EURO
- uz_LATN_UZ
- zh_CN_PINYIN
- zh_CN_STROKE
- zh_HK_STROKE
- zh_TW_STROKE
uz_LATN_UZ has been handled with an ad-hoc rule since LATN means Latin and the country is UZ.
One of the impact is the following flag, that is not showing correctly for the value de_DE_EURO (e.g.):
> Handle LocaleSidKeys with multiple underscores + (Latin)

- CHANGES.md
- README.md
- test/main/default/package.xml
- test/main/default/settings/Account.settings-meta.xml
Add relate a contact to multiple accounts as metadata to deploy with other test dependencies
> Remove test setup manual step

- CHANGES.md
- addon/popup.js
> [popup] Reduce the chances to hit limit on EntityDefinition query for large orgs

- addon/data-export-test.js
- addon/data-export.css
- addon/data-export.js
- addon/data-import-test.js
- addon/data-import.js
- addon/test-framework.js
Hi! I've created this PR to implement the feature described in #134.
Test evidence after opening the test-framework page:
Thank you!
> Add feature "[data-export] Delete button"

- CHANGES.md
- addon/button.js
Since Winter 24, some UI changes in flow builder affect the usability of the popup icon.
There is an improvement which is in progress to let users decide where they want to place their icon.
Since this is not finished yet, this PR adds a margin to the button in flow builder to prevent the overlap
> [popup] Move popup icon in flow builder

- CHANGES.md
- addon/inspect.js
Text is substituted dynamically to show/hide table borders.
> Dynamically display text in show / hide borders menu.

- CHANGES.md
- addon/popup.js
Add a check if `durableId` was not previously set but the entry is already added into the map.
#218 
- [ X ] I have read and understand the [Contributions section](https://github.com/tprouvot/Salesforce-Inspector-reloaded#contributions)
- [ X ] Target branch is releaseCandidate and not master
- [ X ] I have performed a self-review of my code
- [ X ] I ran the [unit tests](https://github.com/tprouvot/Salesforce-Inspector-reloaded#unit-tests) and my PR does not break any tests
- [ X ] I documented the changes I've made on the [CHANGES.md](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/master/CHANGES.md) and followed actual conventions
- [ N/A ] I added a new section on [how-to.md](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/master/docs/how-to.md) …
> Fix for #218 adding durableId if unset

- CHANGES.md
- addon/popup.js
**Overview:**
This pull request introduces an improvement to the shortcut search functionality. Previously, the search was limited to matching only the beginning of shortcut titles. With this update, users can now search for shortcuts by using terms that appear anywhere within the shortcut title, for example: previously, in order to find "Company Information", you couldn't just type "Info", but now you can. This change better aligns with Salesforce's setup search functionality witch allows searching for terms that appear anywhere in the node title. In addition this change is beneficial since users don't always remember the exact title and it's beginning.
**Testing**
This feature has been tested across different environments to ensure compatibility and smooth integration with existing …
> Enhance Shortcut Search to Include Any Part of Title, not only beginning

- CHANGES.md
- addon/data-export-test.js
- addon/data-export.js
Fix for also enabling the delete button when only one record is queried/filtered. Tests have been included and the full test suite has been executed successfully.
> Fix Delete Button when only one record is filtered

- CHANGES.md
- addon/data-export.js
- addon/data-import-test.js
- addon/data-import.js
Fixing the Delete button for the cases where the "Tooling API" option has been selected when querying
Included logic for sending the apiType as a parameter to the data-import.
[Issue 254](https://github.com/tprouvot/Salesforce-Inspector-reloaded/issues/254)
> fix: Fix for issue #254

- addon/popup.js
just fix a missing key on react (error on chrome extension log)
none
> Fix popup react error key missing

- addon/popup.css
Remove the color override on `a:link` (but kept it on `a:visited`).
The override on unvisited links was causing them to be unreadable on SLDS button with the brand style. 
It did not notice any issue remove the `a:link` style from the custom CSS.
> Bugfix: remove link CSS override

- CHANGES.md
- addon/button.js
- addon/manifest-template.json
- addon/manifest.json
- addon/popup.js
When users clicked "Show fields API names" they were not able to hide the added information, this feature has been requested by several users
N/A
> [feature] Add hide fields api name button

- addon/background.js
The beta version was not working anymore on orgs protected by Microsoft Defender for Cloud Apps (.mcas.ms domain).
This PR contains a fix for that issue. 
Not the most elegant solution, but apparently `chrome.cookies.get()` does not work as expect when Microsoft Defender for Cloud Apps is used, which is why I added a check on the domain before.
> Fix getSfHost on .mcas.ms domains

- addon/popup.js
When calling the Salesforce Status API, the list of maintenances returned in the JSON response is not filtered by date, so the previous release is included in the response.
The goal is to filter the result so only the future releases will be displayed.
Code example here: https://jsfiddle.net/nc3v1jmy/
Solves #282
> fix: next future release displayed in org tab

- CHANGES.md
- addon/manifest.json
- addon/popup.js
Display API version in the org tab
#293
> [popup] Add API Version to Org tab

- CHANGES.md
- addon/popup.js
Hide RecType field when no record type on record.
Closing #298
> Hide RecType field in popup when field is not set

- CHANGES.md
- addon/data-export-test.js
- addon/data-export.js
Added number of filtered records in data export page
Closes #300
> [data-export] Add number of filtered records

- CHANGES.md
- addon/data-export-test.js
- addon/data-export.js
Add query plan button to get info for the current query, display articles link in order to understand the results and how to improve query perfs
Closing #314
> [data-export] Add query plan to export data

- CHANGES.md
- addon/data-export.js
- addon/popup.js
Entering consumer key from data export was failing since the sf host was null.
Removing the input and keep the normal process on Option page.
#338
> [data-export] fix : Remove client id from data export

- CHANGES.md
- addon/options.js
- addon/popup.js
Add option to enable / disable SObject type when data export from an SObject.
#341
> Add option to enable / disable sobject context on data export

- CHANGES.md
- addon/options.js
- docs/how-to.md
Add query templates to Option page
#349
> Add query template to option page

- CHANGES.md
- addon/popup.js
⚠️ Only available on summer 24
Closes #386
> [popup] Add user summary link on popup

- CHANGES.md
- addon/manifest-template.json
- addon/manifest.json
In future releases, setup pages will be hosted on a different [domain](https://help.salesforce.com/s/articleView?id=release-notes.rn_general_setup_domain_prepare.htm&release=246&type=5) (already deployed on scratch orgs).
Closing #389
> [feature] Add new setup page domain

- addon/button.js
- addon/manifest.json
Fix issue on summer24 when loading favicon
> Load extension from chrome extension path instead of github

- CHANGES.md
- addon/data-export.css
- addon/data-export.js
Add download button in data export page
Closes #101
> [data-export] Add download button

- CHANGES.md
- addon/popup.js
Add new link to Object popup tab to display Object permissions details (available on Winter25 orgs)
> Add Object Access link to Object popup tab

- CHANGES.md
- addon/manifest-template.json
- addon/manifest.json
- addon/options.js
- addon/popup.js
- docs/how-to.md
> [options] Add new option to hide buttons and start release 1.26

- CHANGES.md
- addon/popup.js
When updating a user from Salesforce UI after searching for it in the popup and clicking on "Detail" button, the post save redirection goes to the user records and leaves the setup.
With this PR the screen will stay on the user detail page in the setup.
Closes #671
> [popup] Feat/user post save redirect

- CHANGES.md
- addon/inspect.js
> [show-all-data] Add calculated type for formula fiels

- addon/popup.js
Updated call to page reload from instant call to call in callback after debug mode update
https://github.com/tprouvot/Salesforce-Inspector-reloaded/issues/718
> Fixed page reload before actual update on Enable Debug mode action

- CHANGES.md
- addon/inspector.js
Updated getLinkTarget function to handle empty parameter.
https://github.com/tprouvot/Salesforce-Inspector-reloaded/issues/716
> [fix] Event Monitor doesn't load on Edge

- CHANGES.md
- addon/inspect.js
For objects that have no "Name" field, use the one available in the metadata api "nameField":
#806
> [feat] #806 :  Use nameField on Show All Data page

- CHANGES.md
- addon/field-creator.js
This PR fixes issue #787 where empty lines in picklist values were causing deployment errors in the Field Creator feature. The changes include:
- Modified picklist value processing in field-creator.js to:
- Split values by newlines
- Trim each value
- Filter out empty values
- Map remaining values to required format
- Updated CHANGES.md to document the fix
Fixes #787
> fix: Handle empty lines in picklist values for field creator (fixes #787)

- CHANGES.md
- addon/inspect.js
This PR implements a toggle display for polymorphic reference types in the "Show All Data" view. When a field has more than 5 referenceTo types, only the first 5 are shown along with a "+X more" link. Clicking the link expands to show the full list with a "Show less" option.
Collapsed View(Default):
Expanded View:
This improves readability and user experience when dealing with polymorphic fields like WhoId, WhatId, etc.
Fixes [#865](https://github.com/tprouvot/Salesforce-Inspector-reloaded/issues/865)
- [ Done] I have read and understand the [Contributions section](https://github.com/tprouvot/Salesforce-Inspector-reloaded#contributions)
- [ Done] Target branch is releaseCandidate and not master
- [ Done] I have performed a self-review of my code
- [ Done but] I ran the [unit …
> Limit number of polymorphic reference types displayed in 'Show All Data' tooltip (fixes #865)
